### ISSUE TITLE
Experimenting with Swift wrapper around Struct Specfile/project.yml

### ISSUE THREAD

**Issue by maximkhatskevich** [maximkhatskevich/MKHProjGen#1]
@jcampbell05 @lyptt take a look at this, let me know what do you think :)

https://github.com/maximkhatskevich/MKHProjGen/blob/master/Example/Spec.swift

**Comment by jcampbell05** [comment]
Looks pretty awesome :) Nice wrapper for people who want to use it in swift :)

**Comment by mxkh72** [comment]
@lyptt this project will partially solve this issue: https://github.com/lyptt/struct/issues/67 User will not need to define explicitly anything that can be inferred.

**Comment by mxkh72** [comment]
@jcampbell05 @lyptt check this out https://github.com/maximkhatskevich/MKHProjGen/releases/tag/1.0.8 Your feedback is very welcome!
